# Generated by Django 5.2.10 on 2026-02-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_name',
            new_name='company',
        ),
    ]
